/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetopoo;

import MyFrames.Categoria;
import MyFrames.Forma_PAG2;
import MyFrames.Formas_PAG;
import MyFrames.Produtos;
import MyFrames.Produtos2;
import MyFrames.Vendas;
import MyFrames.Vendas1;

/**
 *
 * @author joaoa
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLImagem = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mnuSair = new javax.swing.JMenuItem();
        mnuCadastro = new javax.swing.JMenu();
        mnuFPag = new javax.swing.JMenuItem();
        mnuCategoria = new javax.swing.JMenuItem();
        mnuProduto = new javax.swing.JMenuItem();
        mnuConsultas = new javax.swing.JMenu();
        mnuProdutos = new javax.swing.JMenuItem();
        mnuFormaPag2 = new javax.swing.JMenuItem();
        mnuCvendas = new javax.swing.JMenuItem();
        mnuVendas = new javax.swing.JMenu();
        mnuVendas1 = new javax.swing.JMenuItem();

        jLImagem.setIcon(new javax.swing.ImageIcon("C:\\Users\\joaoa\\OneDrive\\Desktop\\ChatGPT Image 10 de mar. de 2026, 15_49_33 (1).png")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 419, Short.MAX_VALUE)
        );

        mnuFile.setText("File");

        mnuSair.setText("Sair");
        mnuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSairActionPerformed(evt);
            }
        });
        mnuFile.add(mnuSair);

        jMenuBar1.add(mnuFile);

        mnuCadastro.setText("Cadastro");

        mnuFPag.setText("Forma de Pagamento");
        mnuFPag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFPagActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuFPag);

        mnuCategoria.setText("Categoria");
        mnuCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCategoriaActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuCategoria);

        mnuProduto.setText("Produto");
        mnuProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutoActionPerformed(evt);
            }
        });
        mnuCadastro.add(mnuProduto);

        jMenuBar1.add(mnuCadastro);

        mnuConsultas.setText("Consultas");

        mnuProdutos.setText("Produtos");
        mnuProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuProdutosActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuProdutos);

        mnuFormaPag2.setText("Formas de Pagamento");
        mnuFormaPag2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuFormaPag2ActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuFormaPag2);

        mnuCvendas.setText("Vendas");
        mnuCvendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCvendasActionPerformed(evt);
            }
        });
        mnuConsultas.add(mnuCvendas);

        jMenuBar1.add(mnuConsultas);

        mnuVendas.setText("Vendas");

        mnuVendas1.setText("Vendas");
        mnuVendas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuVendas1ActionPerformed(evt);
            }
        });
        mnuVendas.add(mnuVendas1);

        jMenuBar1.add(mnuVendas);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);  
    }//GEN-LAST:event_mnuSairActionPerformed

    private void mnuCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCategoriaActionPerformed
        // TODO add your handling code here:
       Categoria cg = new Categoria();
        Desktop.add(cg);
        cg.setVisible(true);
        
    }//GEN-LAST:event_mnuCategoriaActionPerformed

    private void mnuProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutoActionPerformed
        // TODO add your handling code here:
        Produtos prd = new Produtos();
        Desktop.add(prd);
        prd.setVisible(true);
    }//GEN-LAST:event_mnuProdutoActionPerformed

    private void mnuFPagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFPagActionPerformed
        // TODO add your handling code here:
        Formas_PAG pg = new Formas_PAG();
        Desktop.add(pg);
        pg.setVisible(true);
    }//GEN-LAST:event_mnuFPagActionPerformed

    private void mnuProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuProdutosActionPerformed
        // TODO add your handling code here:
        Produtos2 prd2 = new Produtos2();
        Desktop.add(prd2);
        prd2.setVisible(true);
    }//GEN-LAST:event_mnuProdutosActionPerformed

    private void mnuFormaPag2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuFormaPag2ActionPerformed
        // TODO add your handling code here:
        Forma_PAG2 pg2 = new Forma_PAG2();
        Desktop.add(pg2);
        pg2.setVisible(true);
        
    }//GEN-LAST:event_mnuFormaPag2ActionPerformed

    private void mnuCvendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCvendasActionPerformed
        // TODO add your handling code here:
        Vendas vd = new Vendas();
        Desktop.add(vd);
        vd.setVisible(true);
        
    }//GEN-LAST:event_mnuCvendasActionPerformed

    private void mnuVendas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuVendas1ActionPerformed
        // TODO add your handling code here:
        Vendas1 vd1 = new Vendas1();
        Desktop.add(vd1);
        vd1.setVisible(true);
    }//GEN-LAST:event_mnuVendas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new MainFrame().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JLabel jLImagem;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu mnuCadastro;
    private javax.swing.JMenuItem mnuCategoria;
    private javax.swing.JMenu mnuConsultas;
    private javax.swing.JMenuItem mnuCvendas;
    private javax.swing.JMenuItem mnuFPag;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JMenuItem mnuFormaPag2;
    private javax.swing.JMenuItem mnuProduto;
    private javax.swing.JMenuItem mnuProdutos;
    private javax.swing.JMenuItem mnuSair;
    private javax.swing.JMenu mnuVendas;
    private javax.swing.JMenuItem mnuVendas1;
    // End of variables declaration//GEN-END:variables
}
