/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package MyFrames;

import Dao.CategoriasDAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaoa
 */
public class CategoriaConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form CategoriaConsulta
     */
    public CategoriaConsulta() {
        initComponents();
        configurarTabelaCategorias();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonConsultarCat = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonAtualizarCat = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableconsultarCat = new javax.swing.JTable();

        setClosable(true);
        setTitle("Consultar Categoria");
        setToolTipText("");

        jButtonConsultarCat.setText("Consultar");
        jButtonConsultarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConsultarCatActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonAtualizarCat.setText("Atualizar");
        jButtonAtualizarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarCatActionPerformed(evt);
            }
        });

        jTableconsultarCat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id", "Nome"
            }
        ));
        jScrollPane1.setViewportView(jTableconsultarCat);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonExcluir)
                                .addGap(112, 112, 112)
                                .addComponent(jButtonAtualizarCat))
                            .addComponent(jButtonConsultarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButtonConsultarCat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonAtualizarCat))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConsultarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConsultarCatActionPerformed

        atualizarTabelaCategorias();

    }//GEN-LAST:event_jButtonConsultarCatActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed

            int linhaSelecionada = jTableconsultarCat.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma categoria na tabela para excluir.");
        return;
    }

    int idCategoria = Integer.parseInt(
            jTableconsultarCat.getValueAt(linhaSelecionada, 0).toString()
    );

    int resposta = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir esta categoria?",
            "Confirmar exclusão",
            JOptionPane.YES_NO_OPTION
    );

    if (resposta == JOptionPane.YES_OPTION) {
        CategoriasDAO.excluirCategoria(idCategoria);
        atualizarTabelaCategorias();
    }

    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonAtualizarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarCatActionPerformed

                int linhaSelecionada = jTableconsultarCat.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione uma categoria na tabela para atualizar.");
        return;
    }

    int idCategoria = Integer.parseInt(
            jTableconsultarCat.getValueAt(linhaSelecionada, 0).toString()
    );

    String nomeAtual = jTableconsultarCat.getValueAt(linhaSelecionada, 1).toString();

    String novoNome = JOptionPane.showInputDialog(this, "Digite o novo nome da categoria:", nomeAtual);

    if (novoNome == null || novoNome.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "O nome da categoria não pode ficar vazio.");
        return;
    }

    CategoriasDAO.atualizarCategoria(idCategoria, novoNome);
    atualizarTabelaCategorias();
        
        
    }//GEN-LAST:event_jButtonAtualizarCatActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarCat;
    private javax.swing.JButton jButtonConsultarCat;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableconsultarCat;
    // End of variables declaration//GEN-END:variables

    private void configurarTabelaCategorias() {

            jTableconsultarCat.setModel(new DefaultTableModel(
        new Object[][]{},
        new String[]{"ID", "Nome"}
    ) {
        Class[] types = new Class[]{
            java.lang.Integer.class,
            java.lang.String.class
        };

        public Class getColumnClass(int columnIndex) {
            return types[columnIndex];
        }

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    });

    }
    
    private void atualizarTabelaCategorias() {
    
        CategoriasDAO.consultarCategorias(jTableconsultarCat);

    }
    
}
