/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package MyFrames;

import Conexao.Conexao;
import Dao.ProdutoDAO;
import com.mycompany.projetopoo.MainFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author joaoa
 */
public class Produtos2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Produtos2
     */
    public Produtos2() {
        initComponents();
        carregarComboBoxCategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxProdutos2 = new javax.swing.JComboBox<>();
        jButtonCConsultarProduto = new javax.swing.JButton();
        jButtonExcluirCProd = new javax.swing.JButton();
        jButtonAtualizarCProd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableConsultarProd = new javax.swing.JTable();

        setClosable(true);
        setTitle("Produtos");

        jComboBoxProdutos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxProdutos2ActionPerformed(evt);
            }
        });

        jButtonCConsultarProduto.setText("Consultar");
        jButtonCConsultarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCConsultarProdutoActionPerformed(evt);
            }
        });

        jButtonExcluirCProd.setText("Excluir");
        jButtonExcluirCProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirCProdActionPerformed(evt);
            }
        });

        jButtonAtualizarCProd.setText("Atualizar");
        jButtonAtualizarCProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarCProdActionPerformed(evt);
            }
        });

        jTableConsultarProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Preço", "Estoque", "ID"
            }
        ));
        jScrollPane1.setViewportView(jTableConsultarProd);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxProdutos2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonExcluirCProd, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(146, 146, 146)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCConsultarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAtualizarCProd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxProdutos2)
                    .addComponent(jButtonCConsultarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonExcluirCProd, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(jButtonAtualizarCProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxProdutos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxProdutos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxProdutos2ActionPerformed

    private void jButtonCConsultarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCConsultarProdutoActionPerformed
    Object itemSelecionado = jComboBoxProdutos2.getSelectedItem();

    if (itemSelecionado == null) {
        JOptionPane.showMessageDialog(this, "Selecione uma categoria.");
        return;
    }

    String categoria = itemSelecionado.toString();

    if (categoria.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecione uma categoria.");
        return;
    }

    ProdutoDAO.consultarProdutosPorCategoria(categoria, jTableConsultarProd);
    }//GEN-LAST:event_jButtonCConsultarProdutoActionPerformed

    private void jButtonExcluirCProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirCProdActionPerformed

            int linhaSelecionada = jTableConsultarProd.getSelectedRow();

    if (linhaSelecionada == -1) {
        JOptionPane.showMessageDialog(this, "Selecione um produto na tabela para excluir.");
        return;
    }

    int idProduto = Integer.parseInt(jTableConsultarProd.getValueAt(linhaSelecionada, 3).toString());

    int resposta = JOptionPane.showConfirmDialog(
            this,
            "Deseja realmente excluir este produto?",
            "Confirmar exclusão",
            JOptionPane.YES_NO_OPTION
    );

    if (resposta == JOptionPane.YES_OPTION) {
        ProdutoDAO.excluirProduto(idProduto);

        Object itemSelecionado = jComboBoxProdutos2.getSelectedItem();
        if (itemSelecionado != null) {
            String categoria = itemSelecionado.toString();
            ProdutoDAO.consultarProdutosPorCategoria(categoria, jTableConsultarProd);
        }
    }

    }//GEN-LAST:event_jButtonExcluirCProdActionPerformed

    private void jButtonAtualizarCProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarCProdActionPerformed

            Object itemSelecionado = jComboBoxProdutos2.getSelectedItem();

    if (itemSelecionado == null) {
        JOptionPane.showMessageDialog(this, "Selecione uma categoria para atualizar a consulta.");
        return;
    }

    String categoria = itemSelecionado.toString();

    if (categoria.trim().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Selecione uma categoria para atualizar a consulta.");
        return;
    }

    ProdutoDAO.consultarProdutosPorCategoria(categoria, jTableConsultarProd);

    }//GEN-LAST:event_jButtonAtualizarCProdActionPerformed

        private void carregarComboBoxCategoria(){
        var conn = Conexao.conectar();
        
        try {
            String sql = "SELECT nome_categoria FROM categorias";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
            jComboBoxProdutos2.addItem(rs.getString("nome_categoria"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro!");
            System.getLogger(MainFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarCProd;
    private javax.swing.JButton jButtonCConsultarProduto;
    private javax.swing.JButton jButtonExcluirCProd;
    private javax.swing.JComboBox<String> jComboBoxProdutos2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableConsultarProd;
    // End of variables declaration//GEN-END:variables
}


