/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package MyFrames;

import Conexao.Conexao;
import com.mycompany.projetopoo.MainFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaoa
 */
public class Vendas1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vendas1
     */
    public Vendas1() {
        initComponents();
        carregarComboBoxCategoria();
        carregarComboBoxProdutoPorCategoria();
        carregarComboBoxFormaPagamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxProduto = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTotalVendas = new javax.swing.JTextField();
        jButtonConcluirVenda = new javax.swing.JButton();
        jComboBoxFormaPagamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Vendas");

        jLabel1.setText("Categoria");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBoxCategoria.setToolTipText("");
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        jLabel2.setText("Produto");

        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jLabel3.setText("Quantidade");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Preço", "Quantidade"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButtonAddItem.setText("Adicionar item");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Preço"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Lista da venda");

        jLabel5.setText("Valor total da venda:");

        jTextFieldTotalVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalVendasActionPerformed(evt);
            }
        });

        jButtonConcluirVenda.setText("Concluir venda");
        jButtonConcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirVendaActionPerformed(evt);
            }
        });

        jComboBoxFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormaPagamentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Forma de pagamento:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButtonAddItem, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldTotalVendas))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonConcluirVenda, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jComboBoxFormaPagamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddItem)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextFieldTotalVendas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConcluirVenda)
                        .addGap(19, 19, 19)))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
         carregarComboBoxProdutoPorCategoria();
         
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        // TODO add your handling code here
        String produto = (String) jComboBoxProduto.getSelectedItem();
        String qtdStr = txtQuantidade.getText();

        if(produto == null || produto.equals("") || qtdStr.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
            return;
        }

        int quantidade = 0;
        try {
            quantidade = Integer.parseInt(qtdStr);
            if(quantidade <= 0){
                JOptionPane.showMessageDialog(rootPane, "Quantidade deve ser maior que zero!");
                return;
            }
        } catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, "Quantidade inválida!");
            return;
        }

        
        int idProduto = 0;
        try {
            var conn = Conexao.conectar();
            String sql = "SELECT id FROM produto WHERE nome = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, produto);
            ResultSet rs = stmt.executeQuery();
            if(rs.next()){
                idProduto = rs.getInt("id"); 
            } else {
                JOptionPane.showMessageDialog(rootPane, "Produto não encontrado!");
                return;
            }
        } catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar produto!");
            ex.printStackTrace();
            return;
        }

      
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{idProduto, produto, quantidade});

        
        txtQuantidade.setText("");
        
        atualizarListaVenda();
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jButtonConcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirVendaActionPerformed
        
        
        
    }//GEN-LAST:event_jButtonConcluirVendaActionPerformed

    private void jComboBoxFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormaPagamentoActionPerformed
        // TODO add your handling code here:
        atualizarListaVenda();
    }//GEN-LAST:event_jComboBoxFormaPagamentoActionPerformed

    private void jTextFieldTotalVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalVendasActionPerformed

    private void carregarComboBoxCategoria() {
        var conn = Conexao.conectar();

        try {
            jComboBoxCategoria.removeAllItems();
            jComboBoxCategoria.addItem("Selecione");

            String sql = "SELECT nome_categoria FROM categorias";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                jComboBoxCategoria.addItem(rs.getString("nome_categoria"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar categorias!");
            ex.printStackTrace();
        }
 }
    
    private void carregarComboBoxProdutoPorCategoria() {
        var conn = Conexao.conectar();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        try {
            jComboBoxProduto.removeAllItems(); 

            String categoriaSelecionada = (String) jComboBoxCategoria.getSelectedItem();
            if (categoriaSelecionada == null || categoriaSelecionada.equals("Selecione")) {
                return;             }

            String sql = "SELECT p.id, p.nome, p.preco, p.estoque " +
                         "FROM produto p " +
                         "INNER JOIN categorias c ON p.id_cat = c.id_categoria " +
                         "WHERE c.nome_categoria = ?";

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, categoriaSelecionada);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String nome = rs.getString("nome");
                double preco = rs.getDouble("preco");
                int estoque = rs.getInt("estoque");

                modelo.addRow(new Object[]{id, nome, preco, estoque});
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar produtos!");
            ex.printStackTrace();
        }
  }
    
    
    private void atualizarListaVenda() {
    DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
    DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
    model2.setRowCount(0); 
    String formaPagamento = jComboBoxFormaPagamento.getSelectedItem().toString();
    
    

    String sql2 = "SELECT taxa FROM forma_pagamento WHERE nome_forn_pag = ?";

    PreparedStatement stmt2;
    Double taxa_formaPagamento = 0.0;
        try {
            var conn = Conexao.conectar();
            stmt2 = conn.prepareStatement(sql2);
            stmt2.setString(1, formaPagamento);

            ResultSet rs = stmt2.executeQuery();

            

            if(rs.next()){
                taxa_formaPagamento = rs.getDouble("taxa");
            }
        } catch (SQLException ex) {
            System.getLogger(Vendas1.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    

    double valorTotal = 0;

    try { 
        var conn = Conexao.conectar();

        for (int i = 0; i < model1.getRowCount(); i++) {
            int idProduto = (int) model1.getValueAt(i, 0);
            String produto = (String) model1.getValueAt(i, 1);
            int quantidade = (int) model1.getValueAt(i, 2);

            
            String sql = "SELECT preco FROM produto WHERE id = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setInt(1, idProduto);
            ResultSet rs = stmt.executeQuery();
            double preco = 0;
            if (rs.next()) {
                preco = rs.getDouble("preco");
            }

            double valorItem = (preco * quantidade);
            valorTotal += valorItem;

            
            model2.addRow(new Object[]{produto, quantidade, valorItem});
        }

       valorTotal = valorTotal + (valorTotal * (taxa_formaPagamento / 100));
       jTextFieldTotalVendas.setText(String.format("%.2f", valorTotal));

    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar lista da venda!");
        ex.printStackTrace();
    }
}
    private void carregarComboBoxFormaPagamento(){
        var conn = Conexao.conectar();
        
        try {
            String sql = "SELECT nome_forn_pag FROM forma_pagamento";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
            jComboBoxFormaPagamento.addItem(rs.getString("nome_forn_pag"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro!");
            System.getLogger(MainFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonConcluirVenda;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxFormaPagamento;
    private javax.swing.JComboBox<String> jComboBoxProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldTotalVendas;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
