/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package MyFrames;

import Conexao.Conexao;
import com.mycompany.projetopoo.MainFrame;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author joaoa
 */
public class Vendas1 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vendas1
     */
    public Vendas1() {
        initComponents();
        carregarComboBoxCategoria();
        carregarTableProdutoPorCategoria();
        carregarComboBoxFormaPagamento();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxCategoria = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddItem = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldTotalVendas = new javax.swing.JTextField();
        jButtonConcluirVenda = new javax.swing.JButton();
        jComboBoxFormaPagamento = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxProduto = new javax.swing.JComboBox<>();

        setClosable(true);
        setTitle("Vendas");

        jLabel1.setText("Categoria");

        jComboBoxCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        jComboBoxCategoria.setToolTipText("");
        jComboBoxCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriaActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Preço", "Estoque"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButtonAddItem.setText("Adicionar item");
        jButtonAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddItemActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Quantidade", "Preço", "Subtotal"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel4.setText("Lista da venda");

        jLabel5.setText("Valor total da venda:");

        jTextFieldTotalVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTotalVendasActionPerformed(evt);
            }
        });

        jButtonConcluirVenda.setText("Concluir venda");
        jButtonConcluirVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConcluirVendaActionPerformed(evt);
            }
        });

        jComboBoxFormaPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFormaPagamentoActionPerformed(evt);
            }
        });

        jLabel6.setText("Forma de pagamento:");

        jComboBoxProduto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButtonAddItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(222, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, 0)
                        .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldTotalVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addComponent(jComboBoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5))
                            .addComponent(jButtonConcluirVenda))
                        .addGap(26, 26, 26))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAddItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBoxProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTotalVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonConcluirVenda))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriaActionPerformed
         carregarTableProdutoPorCategoria();
         
    }//GEN-LAST:event_jComboBoxCategoriaActionPerformed

    private void jButtonAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddItemActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        String nome = "";
        double preco = 0;

        int linha = jTable1.getSelectedRow();

        if(linha == -1){
            JOptionPane.showMessageDialog(rootPane, "Selecione um produto!");
            return;
        }

        String produto = jTable1.getValueAt(linha, 1).toString();
        
        String qtdStr = txtQuantidade.getText();

        if(produto == null || produto.equals("") || qtdStr.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Preencha todos os campos!");
            return;
        }

        int quantidade;

        try {

            quantidade = Integer.parseInt(qtdStr);

            if(quantidade <= 0){
                JOptionPane.showMessageDialog(rootPane, "Quantidade deve ser maior que zero!");
                return;
            }

        } catch(NumberFormatException e){

            JOptionPane.showMessageDialog(rootPane, "Quantidade inválida!");
            return;
        }

        try {

            var conn = Conexao.conectar();

            String sql = "SELECT nome, preco FROM produto WHERE nome = ?";
            PreparedStatement stmt = conn.prepareStatement(sql);

            stmt.setString(1, produto);

            ResultSet rs = stmt.executeQuery();

//            if(rs.next()){
//                nome = rs.getString("nome");
//                preco = rs.getDouble("preco");
//                
//            } 
//            else{
//                JOptionPane.showMessageDialog(rootPane, "Produto não encontrado!");
//                return;
//            }
            while(rs.next()){

                nome = rs.getString("nome");    
                preco = rs.getDouble("preco");

                int idProduto = Integer.parseInt(jTable1.getValueAt(linha, 0).toString());
                double subtotal = preco * quantidade;
                
                model.addRow(new Object[]{idProduto, nome, quantidade, preco, subtotal});
                   
                
                
            }

        } catch(SQLException ex){

            JOptionPane.showMessageDialog(rootPane, "Erro ao buscar produto!");
            ex.printStackTrace();
            return;
        }

        

       
        

        txtQuantidade.setText("");

        atualizarListaVenda();
    }//GEN-LAST:event_jButtonAddItemActionPerformed

    private void jButtonConcluirVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConcluirVendaActionPerformed
        
        concluirVenda();
        
    }//GEN-LAST:event_jButtonConcluirVendaActionPerformed

    private void jComboBoxFormaPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFormaPagamentoActionPerformed
        // TODO add your handling code here:
        atualizarListaVenda();
    }//GEN-LAST:event_jComboBoxFormaPagamentoActionPerformed

    private void jTextFieldTotalVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTotalVendasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTotalVendasActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int linha = jTable1.getSelectedRow();

        String produto = jTable1.getValueAt(linha, 0).toString();
    }//GEN-LAST:event_jTable1MouseClicked

    private void carregarComboBoxCategoria() {
        var conn = Conexao.conectar();

        try {
            jComboBoxCategoria.removeAllItems();
            jComboBoxCategoria.addItem("Selecione");

            String sql = "SELECT nome_categoria FROM categorias";
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                jComboBoxCategoria.addItem(rs.getString("nome_categoria"));
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar categorias!");
            ex.printStackTrace();
        }
 }
    
    private void carregarTableProdutoPorCategoria() {
        var conn = Conexao.conectar();
        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0);
        
        try {
            

            String categoriaSelecionada = (String) jComboBoxCategoria.getSelectedItem();
            if (categoriaSelecionada == null || categoriaSelecionada.equals("Selecione")) {
                return;             }

            String sql = "SELECT p.id, p.nome, p.preco, p.estoque " +
                         "FROM produto p " +
                         "INNER JOIN categorias c ON p.id_cat = c.id_categoria " +
                         "WHERE c.nome_categoria = ?";

            PreparedStatement stmt = conn.prepareStatement(sql);
            stmt.setString(1, categoriaSelecionada);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                int id = rs.getInt("id");
                String nome = rs.getString("nome");
                double preco = rs.getDouble("preco");
                int estoque = rs.getInt("estoque");

                modelo.addRow(new Object[]{id, nome, preco, estoque});
            }

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar produtos!");
            ex.printStackTrace();
        }
  }
    
    
    private void atualizarListaVenda() {
    DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
    DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();
    
    String formaPagamento = jComboBoxFormaPagamento.getSelectedItem().toString();
    
    

    String sql2 = "SELECT taxa FROM forma_pagamento WHERE nome_forn_pag = ?";

    PreparedStatement stmt2;
    Double taxa_formaPagamento = 0.0;
        try {
            var conn = Conexao.conectar();
            stmt2 = conn.prepareStatement(sql2);
            stmt2.setString(1, formaPagamento);

            ResultSet rs = stmt2.executeQuery();

            

            if(rs.next()){
                taxa_formaPagamento = rs.getDouble("taxa");
            }
        } catch (SQLException ex) {
            System.getLogger(Vendas1.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }

    

    double valorTotal = 0;

 //   try { 
   //     var conn = Conexao.conectar();

        for (int i = 0; i < model2.getRowCount(); i++) {
        
                double subtotal = Double.parseDouble(model2.getValueAt(i, 4).toString());
                valorTotal += subtotal;
        
        }

       valorTotal = valorTotal + (valorTotal * (taxa_formaPagamento / 100));
       jTextFieldTotalVendas.setText(String.format("%.2f", valorTotal));

//    } catch (SQLException ex) {
  //      JOptionPane.showMessageDialog(rootPane, "Erro ao atualizar lista da venda!");
//        ex.printStackTrace();
  //  }
}
    private void carregarComboBoxFormaPagamento(){
        var conn = Conexao.conectar();
        
        try {
            String sql = "SELECT nome_forn_pag FROM forma_pagamento";
            
            PreparedStatement stmt = conn.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            
            while(rs.next()){
            jComboBoxFormaPagamento.addItem(rs.getString("nome_forn_pag"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro!");
            System.getLogger(MainFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
    
    
    //Criando o metodo de concluir vendas
    private void concluirVenda() {
    DefaultTableModel model2 = (DefaultTableModel) jTable2.getModel();

    if (model2.getRowCount() == 0) {
        JOptionPane.showMessageDialog(rootPane, "Adicione pelo menos um item à venda!");
        return;
    }

    Object formaSelecionada = jComboBoxFormaPagamento.getSelectedItem();

    if (formaSelecionada == null) {
    JOptionPane.showMessageDialog(rootPane, "Selecione uma forma de pagamento!");
    return;
    }

    String formaPagamento = formaSelecionada.toString();

    if (formaPagamento.trim().isEmpty()) {
    JOptionPane.showMessageDialog(rootPane, "Selecione uma forma de pagamento!");
    return;
    }

    if (formaPagamento == null || formaPagamento.trim().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "Selecione uma forma de pagamento!");
        return;
    }

    String totalStr = jTextFieldTotalVendas.getText();

    if (totalStr == null || totalStr.trim().isEmpty()) {
        JOptionPane.showMessageDialog(rootPane, "O valor total da venda está vazio!");
        return;
    }

    double valorTotal;

    try {
        valorTotal = Double.parseDouble(totalStr.replace(",", "."));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(rootPane, "Valor total inválido!");
        return;
    }

    var conn = Conexao.conectar();

    try {
        conn.setAutoCommit(false);

        int idFormaPagamento = 0;

        String sqlForma = "SELECT id_form_pagamento FROM forma_pagamento WHERE nome_forn_pag = ?";
        PreparedStatement stmtForma = conn.prepareStatement(sqlForma);
        stmtForma.setString(1, formaPagamento);
        ResultSet rsForma = stmtForma.executeQuery();

        if (rsForma.next()) {
            idFormaPagamento = rsForma.getInt("id_form_pagamento");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Forma de pagamento não encontrada!");
            conn.rollback();
            return;
        }

        String sqlVenda = "INSERT INTO vendas (id_form_pag, valor_total) VALUES (?, ?)";
        PreparedStatement stmtVenda = conn.prepareStatement(sqlVenda, PreparedStatement.RETURN_GENERATED_KEYS);
        stmtVenda.setInt(1, idFormaPagamento);
        stmtVenda.setDouble(2, valorTotal);
        stmtVenda.executeUpdate();

        ResultSet rsVenda = stmtVenda.getGeneratedKeys();
        int idVenda = 0;

        if (rsVenda.next()) {
            idVenda = rsVenda.getInt(1);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Erro ao gerar ID da venda!");
            conn.rollback();
            return;
        }

        String sqlItem = "INSERT INTO item_venda (id_prod, id_vend, quantidade, preco_unitario, subtotal) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement stmtItem = conn.prepareStatement(sqlItem);

        String sqlEstoque = "UPDATE produto SET estoque = estoque - ? WHERE id = ?";
        PreparedStatement stmtEstoque = conn.prepareStatement(sqlEstoque);

        for (int i = 0; i < model2.getRowCount(); i++) {
            int idProduto = Integer.parseInt(model2.getValueAt(i, 0).toString());
            int quantidade = Integer.parseInt(model2.getValueAt(i, 2).toString());
            double preco = Double.parseDouble(model2.getValueAt(i, 3).toString());
            double subtotal = Double.parseDouble(model2.getValueAt(i, 4).toString());

            stmtItem.setInt(1, idProduto);
            stmtItem.setInt(2, idVenda);
            stmtItem.setInt(3, quantidade);
            stmtItem.setDouble(4, preco);
            stmtItem.setDouble(5, subtotal);
            stmtItem.executeUpdate();

            stmtEstoque.setInt(1, quantidade);
            stmtEstoque.setInt(2, idProduto);
            stmtEstoque.executeUpdate();
        }

        conn.commit();

        JOptionPane.showMessageDialog(rootPane, "Venda concluída com sucesso!");

        limparTelaVenda();

    } catch (SQLException ex) {
        try {
            conn.rollback();
        } catch (SQLException e) {
            e.printStackTrace();
        }

        JOptionPane.showMessageDialog(rootPane, "Erro ao concluir venda:" + ex.getMessage());
        ex.printStackTrace();

    } finally {
        try {
            conn.setAutoCommit(true);
            conn.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddItem;
    private javax.swing.JButton jButtonConcluirVenda;
    private javax.swing.JComboBox<String> jComboBoxCategoria;
    private javax.swing.JComboBox<String> jComboBoxFormaPagamento;
    private javax.swing.JComboBox<String> jComboBoxProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldTotalVendas;
    private javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables

    private void limparTelaVenda() {

            ((DefaultTableModel) jTable2.getModel()).setRowCount(0);
    txtQuantidade.setText("");
    jTextFieldTotalVendas.setText("");

    if (jComboBoxCategoria.getItemCount() > 0) {
        jComboBoxCategoria.setSelectedIndex(0);
    }

    atualizarListaVenda();
        
    }
}
